- name: Check if the file exists
  ansible.builtin.stat:
    path: /tests/test_file
  register: file_result

- name: Run first playbook
  ansible.builtin.command:
    cmd: ansible-playbook {{ first_playbook_path }}
  delegate_to: localhost
  when: not file_result.stat.exists

- name: Include tasks from my_tasks1.yml
  include_tasks: create.yml

- name: Run second playbook
  ansible.builtin.command:
    cmd: ansible-playbook {{ second_playbook_path }}
  delegate_to: localhost

- name: Include tasks from my_tasks2.yml
  include_tasks: remove.yml

  # also remove the file as well.
